### ISSUE TITLE
rbuild create branch failed with traceback

### ISSUE THREAD

**Issue by mikjo** [sassoftware/rbuild#1]
While following the install instructions at http://sassoftware.github.io/appengine/quickstart.html#installation I got to creating the example branch:

    $ rbuild create branch
    Project name (required): example
    Branch name (required): 1
    Branch description (optional):
    Namespace (blank for default):

    ERROR: An unexpected condition has occurred in rBuild.  This is
    most likely due to insufficient handling of erroneous input, but
    may be some other bug.  In either case, please report the error at
    http://opensource.sas.com/its/ and attach to the issue the file
    /home/mikjo/.rbuild/tracebacks/rbuild-error-XLoPXa.txt

    To get a debug prompt, rerun the command with the --debug-all argument.

    For more information, go to:
    https://opensource.sas.com/conarywiki/index.php/Conary:How_To_File_An_Effective_Bug_Report

    Error details follow:

    /srv/code/appengine/include/robj/proxy.py:32
    TypeError: A list type is required for this method.

    The complete related traceback has been saved as /home/mikjo/.rbuild/tracebacks/rbuild-error-XLoPXa.txt

**Comment by mikjo** [comment]
Full traceback:

    $ cat /home/mikjo/.rbuild/tracebacks/rbuild-error-XLoPXa.txt
    exceptions.TypeError: A list type is required for this method.

    Traceback (most recent call last):
      File "/usr/bin/rbuild", line 25, in <module>
        sys.exit(main.main(sys.argv))
      File "/srv/code/appengine/include/rbuild/internal/main.py", line 292, in main
        return _main(argv, RbuildMain)
      File "/srv/code/appengine/include/rbuild/internal/main.py", line 284, in _main
        return 1
      File "/srv/code/appengine/include/conary/lib/mainhandler.py", line 270, in main
        return self.runCommand(thisCommand, cfg, argSet, otherArgs, **kw)
      File "/srv/code/appengine/include/rbuild/internal/main.py", line 188, in runCommand
        raise e, None, exc_info[2]
      File "/srv/code/appengine/include/rbuild/pluginapi/command.py", line 232, in runCommand
        return subCommand.runCommand(handle, argSet, args[1:])
      File "/usr/share/rbuild/plugins/createprojectbranch.py", line 167, in runCommand
        platforms = rb.listPlatforms()
      File "/srv/code/appengine/include/rbuild/facade/rbuilderfacade.py", line 1067, in listPlatforms
        return client.listPlatforms()
      File "/srv/code/appengine/include/rbuild/facade/rbuilderfacade.py", line 722, in listPlatforms
        for platform in self.api.platforms.platform:
      File "/srv/code/appengine/include/robj/proxy.py", line 32, in wrapper
        raise TypeError, 'A list type is required for this method.'

    Full stack:
    exceptions.TypeError: A list type is required for this method.

    Traceback (most recent call first):
      File "/srv/code/appengine/include/robj/proxy.py", line 32, in wrapper
        raise TypeError, 'A list type is required for this method.'
                       args : ()
                     kwargs : {}
                       self : <robj.rObj(platform)>
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/facade/rbuilderfacade.py", line 722, in listPlatforms
        for platform in self.api.platforms.platform:
                        ret : []
                       self : <rbuild.facade.rbuilderfacade.RbuilderRESTClient object at 0x3025f90>
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/facade/rbuilderfacade.py", line 1067, in listPlatforms
        return client.listPlatforms()
                     client : <rbuild.facade.rbuilderfacade.RbuilderRESTClient object at 0x3025f90>
                       self : <rbuild.facade.rbuilderfacade.RbuilderFacade object at 0x3025910>
      **********************************************************************

      File "/usr/share/rbuild/plugins/createprojectbranch.py", line 167, in runCommand
        platforms = rb.listPlatforms()
                     argSet : {'branch': '1', 'description': None, 'namespace': None, 'project': 'example'}
                       args : ['create', 'branch']
                     handle : <RbuildHandle at 0x30bab00>
                         rb : <rbuild.facade.rbuilderfacade.RbuilderFacade object at 0x3025910>
                       self : <rbuild_plugins.createprojectbranch.CreateBranchCommand object at 0x3025ed0>
                         ui : <rbuild.ui.UserInterface object at 0x3025a10>
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/pluginapi/command.py", line 232, in runCommand
        return subCommand.runCommand(handle, argSet, args[1:])
                     argSet : {'branch': '1', 'description': None, 'namespace': None, 'project': 'example'}
                       args : ['/usr/bin/rbuild', 'create', 'branch']
                commandName : 'branch'
                     handle : <RbuildHandle at 0x30bab00>
                       self : <rbuild_plugins.create.CreateCommand object at 0x3025b90>
                 subCommand : <rbuild_plugins.createprojectbranch.CreateBranchCommand object at 0x3025ed0>
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/internal/main.py", line 188, in runCommand
        raise e, None, exc_info[2]
                          _ : <rbuild.rbuildcfg.RbuildConfiguration object at 0x2ea6310>
                     argSet : {'branch': '1', 'description': None, 'namespace': None, 'project': 'example'}
                       args : ['/usr/bin/rbuild', 'create', 'branch']
                        cfg : <rbuild.rbuildcfg.RbuildConfiguration object at 0x2ea6310>
                          e : TypeError('A list type is required for this method.',)
                   exc_info : (<type 'exceptions.TypeError'>, TypeError('A list type is required for this method.',), <traceback object at 0x304b488>)
                     lsprof : False
                     passwd : 'Hyperph0nically'
                       self : <rbuild.internal.main.RbuildMain object at 0x2e9efd0>
                thisCommand : <rbuild_plugins.create.CreateCommand object at 0x3025b90>
      **********************************************************************

      File "/srv/code/appengine/include/conary/lib/mainhandler.py", line 270, in main
        return self.runCommand(thisCommand, cfg, argSet, otherArgs, **kw)
                     argSet : {'branch': '1', 'description': None, 'namespace': None, 'project': 'example'}
                       argv : ['/usr/bin/rbuild', 'create', 'branch']
                        cfg : <rbuild.rbuildcfg.RbuildConfiguration object at 0x2ea6310>
                     cfgMap : {}
                commandName : 'create'
                      debug : False
                   debugAll : False
                         kw : {}
                     kwargs : {
                               'addConfigOptions': False,
                               'addDebugOptions': False,
                               'addVerboseOptions': False,
                               'defaultGroup': 'Common Options',
                               'description': '\n    Commands for creating projects, branches, and other objects\n    ',
                               'hobbleShortOpts': False,
                               'useHelp': False,
                               'version': None}
                  newArgSet : {}
                  optionSet : <Values at 0x3030710: {'help': None, 'domain-name': None, 'message': None, 'label': None, 'from-file': None, 'no-create': None, 'short-name': None, 'project': None, 'verbose': None, 'entitlement': None, 'namespace': None, 'skip-default-config': None, 'platform': None, 'branch': None, 'upstream-url': None, 'config': None, 'email': None, 'username': None, 'description': None, 'to-file': None, 'external': None, 'password': None, 'descrption': None, 'stage': None, 'user-name': None, 'name': None, 'admin': None, 'quiet': None, 'config-file': None, 'full-name': None, 'auth-type': None, 'lsprof': None}>
                  otherArgs : ['/usr/bin/rbuild', 'create', 'branch']
                     params : {
                               'Common Options': {
                                     'config': [3, (1, 'Set config KEY to VALUE', "'KEY VALUE'")],
                                     'config-file': [3, (1, 'Read PATH config file', 'PATH')],
                                     'help': (0, 'SUPPRESSHELP'),
                                     'lsprof': [0, 'SUPPRESSHELP'],
                                     'quiet': [0, (1, 'Quiet operation, intended for scripting')],
                                     'skip-default-config': [0, (1, "Don't read default configs")],
                                     'stage': [1, (1, 'Specify the stage to use')],
                                     'verbose': [0, (1, 'Display more detailed information where available')]},
                               'admin': 0,
                               'auth-type': 1,
                               'branch': 1,
                               'description': 1,
                               'descrption': 1,
                               'domain-name': 1,
                               'email': 1,
                               'entitlement': 1,
                               'external': 0,
                               'from-file': ('-f', 1),
                               'full-name': 1,
                               'label': 1,
                               'message': ('-m', 1),
                               'name': 1,
                               'namespace': 1,
                               'no-create': 0,
                               'password': 1,
                               'platform': 1,
                               'project': 1,
                               ...len=25...}
                     parser : <conary.lib.options.OptionParser instance at 0x3020d88>
                       self : <rbuild.internal.main.RbuildMain object at 0x2e9efd0>
            supportedCommands : {
                               'add': <rbuild_plugins.create.CreateCommand object at 0x3025b90>,
                               'build': <rbuild_plugins.build.BuildCommand object at 0x3025dd0>,
                               'cancel': <rbuild_plugins.cancel.CancelCommand object at 0x3025a90>,
                               'checkout': <rbuild_plugins.checkout.CheckoutCommand object at 0x3025e50>,
                               'config': <rbuild_plugins.config.ConfigCommand object at 0x3025c50>,
                               'create': <rbuild_plugins.create.CreateCommand object at 0x3025b90>,
                               'delete': <rbuild_plugins.delete.DeleteCommand object at 0x3025c90>,
                               'deploy': <rbuild_plugins.images.LaunchCommand object at 0x3025cd0>,
                               'disable': <rbuild_plugins.enable.EnablePlatformCommand object at 0x3025c10>,
                               'edit': <rbuild_plugins.edit.EditCommand object at 0x3025d50>,
                               'enable': <rbuild_plugins.enable.EnablePlatformCommand object at 0x3025c10>,
                               'help': <rbuild.internal.helpcommand.HelpCommand object at 0x2ea65d0>,
                               'init': <rbuild_plugins.init.InitCommand object at 0x3025ad0>,
                               'launch': <rbuild_plugins.images.LaunchCommand object at 0x3025cd0>,
                               'list': <rbuild_plugins.list.ListCommand object at 0x3025b50>,
                               'promote': <rbuild_plugins.promote.PromoteCommand object at 0x3025e90>,
                               'query': <rbuild_plugins.list.ListCommand object at 0x3025b50>,
                               'rebase': <rbuild_plugins.rebase.RebaseCommand object at 0x3025e10>,
                               'rm': <rbuild_plugins.delete.DeleteCommand object at 0x3025c90>,
                               'show': <rbuild_plugins.show.ShowCommand object at 0x3025d10>,
                               ...len=23...}
                thisCommand : <rbuild_plugins.create.CreateCommand object at 0x3025b90>
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/internal/main.py", line 284, in _main
        return 1
                       argv : ['/usr/bin/rbuild', 'create', 'branch']
                   debugAll : False
      **********************************************************************

      File "/srv/code/appengine/include/rbuild/internal/main.py", line 292, in main
        return _main(argv, RbuildMain)
                       argv : ['/usr/bin/rbuild', 'create', 'branch']
      **********************************************************************

      File "/usr/bin/rbuild", line 25, in <module>
        sys.exit(main.main(sys.argv))
      **********************************************************************

**Comment by mikjo** [comment]
I wasn't a failure to have an enabled platform:

    $ rbuild list platforms
    LABEL                              ENABLED
    centos6.rpath.com@rpath:centos-6e  true
